# Generated by Django 5.2 on 2025-11-04 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=15)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('documento_adopcion', models.FileField(blank=True, null=True, upload_to='adopciones/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proceso de adopcion',
                'verbose_name_plural': 'Procesos de adopcion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
