# Generated by Django 5.2 on 2025-11-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adopcion', '0001_initial'),
        ('Mascota', '0001_initial'),
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adopciones', to='Mascota.mascota'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adopciones', to='Persona.persona'),
        ),
        migrations.AddConstraint(
            model_name='adopcion',
            constraint=models.UniqueConstraint(fields=('mascota', 'persona'), name='unique_mascota_persona_en_adopcion'),
        ),
    ]
