# Generated by Django 5.2.4 on 2025-11-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='estado',
            field=models.CharField(default='Activo', max_length=15),
        ),
    ]
