# Generated by Django 5.2 on 2025-11-04 04:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adopcion', '0001_initial'),
        ('Especie', '0001_initial'),
        ('Persona', '0001_initial'),
        ('Raza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('sexo', models.CharField(max_length=6)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad_aproximada', models.PositiveSmallIntegerField(blank=True, help_text='Edad estimada en años cuando no existe fecha de nacimiento exacta.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado_salud', models.CharField(max_length=12)),
                ('descripcion', models.TextField(blank=True)),
                ('vacunas_al_dia', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateField()),
                ('ubicacion_refugio', models.CharField(blank=True, max_length=120)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('adoptantes', models.ManyToManyField(blank=True, related_name='mascotas', through='Adopcion.Adopcion', to='Persona.persona')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='Especie.especie')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='Raza.raza')),
            ],
        ),
    ]
